#!/usr/bin/env python3
"""Downloads the interface fonts into web/fonts and generates web/css/fonts.css.

Only the subsets the interface and conversations actually need are kept:
latin, latin-ext, cyrillic, cyrillic-ext. Greek and Vietnamese are dropped —
hundreds of extra kilobytes for alphabets the product does not use.
"""
import os, re, subprocess, sys

ROOT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "web")
FONTS = os.path.join(ROOT, "fonts")
CSS_OUT = os.path.join(ROOT, "css", "fonts.css")
URL = ("https://fonts.googleapis.com/css2?"
       "family=IBM+Plex+Serif:wght@500;600;700"
       "&family=Bitter:wght@500;600;700"
       "&family=Inter:wght@400;500;600;700"
       "&display=swap")
KEEP = {"latin", "latin-ext", "cyrillic", "cyrillic-ext"}
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")


def get(url: str) -> bytes:
    return subprocess.run(["curl", "-sSfL", "-A", UA, url],
                          check=True, capture_output=True).stdout


def main():
    os.makedirs(FONTS, exist_ok=True)
    css = get(URL).decode()

    # The response arrives as "/* subset */ @font-face {...}" blocks.
    blocks = re.findall(r"/\* (\S+) \*/\s*(@font-face \{.*?\})", css, re.S)
    if not blocks:
        sys.exit("could not parse the font service response")

    out, kept, total = [], 0, 0
    for subset, block in blocks:
        total += 1
        if subset not in KEEP:
            continue
        fam = re.search(r"font-family: '([^']+)'", block).group(1)
        wght = re.search(r"font-weight: (\d+)", block).group(1)
        src = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
        name = "%s-%s-%s.woff2" % (fam.replace(" ", ""), wght, subset)
        path = os.path.join(FONTS, name)
        if not os.path.exists(path):
            with open(path, "wb") as f:
                f.write(get(src))
        block = block.replace(src, "/fonts/" + name)
        out.append("/* %s */\n%s" % (subset, block))
        kept += 1

    header = (
        "/* Interface fonts, self-hosted rather than fetched from a third party.\n"
        " *\n"
        " * A <link> to an external font CDN is a render-blocking request to\n"
        " * someone else's domain: until it answers, the browser paints\n"
        " * nothing. Measured with a 600 ms CDN response, the app's first\n"
        " * frame appeared only 660 ms after a reload.\n"
        " *\n"
        " * For a messenger deployed inside a closed network it is also a\n"
        " * functional problem: without internet access the fonts never\n"
        " * arrive, and every sign-in discloses the user's address.\n"
        " *\n"
        " * Generated by scripts/fetch-fonts.py; subsets:\n"
        " * latin, latin-ext, cyrillic, cyrillic-ext.\n"
        " */\n\n")
    with open(CSS_OUT, "w") as f:
        f.write(header + "\n\n".join(out) + "\n")

    size = sum(os.path.getsize(os.path.join(FONTS, f)) for f in os.listdir(FONTS))
    print("@font-face: kept %d of %d, %d files, %.0f KB total"
          % (kept, total, len(os.listdir(FONTS)), size / 1024))


if __name__ == "__main__":
    main()
